sudo: false
addons:
  apt:
    packages:
      - python-matplotlib
      - python-numpy
      - python-scipy
      - pandoc
language: python
cache: pip
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install scipy
  - pip install --upgrade .
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade tox-travis
# command to run tests
script: tox
after_success: coveralls
