language: python
cache: pip
python:
  - "2.7"
  - "3.5"
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
# command to install dependencies
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION termcolor six numpy scipy pandas scikit-learn tox-travis
  - python setup.py install
# command to run tests
script: tox
after_success: coveralls