sudo: false
addons:
  apt:
    packages:
      - python-matplotlib
      - python-scipy
      - pandoc
language: python
cache: pip
python:
  - "2.7"
  - "3.5"
# command to install dependencies
virtualenv:
    system_site_packages: true
SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt  
apt-get install python-numpy
apt-get install python-scipy

install:
  - pip install --upgrade pip
  - pip install scipy
  - pip install --upgrade .
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade tox-travis
# command to run tests
script: tox
after_success: coveralls
